# Generated by Django 4.1.7 on 2023-03-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
