# Generated by Django 4.1.5 on 2023-05-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_checkout"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
