# Generated by Django 4.1.5 on 2023-05-22 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0013_delete_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("firstname", models.CharField(blank=True, max_length=25, null=True)),
                ("lastname", models.CharField(blank=True, max_length=25, null=True)),
                ("Address", models.CharField(blank=True, max_length=1000, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.IntegerField(blank=True, null=True)),
                ("phone", models.IntegerField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
