# Generated by Django 4.1.7 on 2023-06-13 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_category_category_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyOrders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Cart",
                        to="core.cart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="core.profile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Newsletter",
        ),
        migrations.DeleteModel(
            name="Offer",
        ),
    ]
