# Generated by Django 4.1.7 on 2023-06-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_myorders_delete_newsletter_delete_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="isPaid",
            field=models.BooleanField(default=False),
        ),
    ]
