# Generated by Django 4.1.7 on 2023-06-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_cart_ispaid"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="orderID",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
