# Generated by Django 4.1.7 on 2023-06-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_cartitems_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
    ]
