# Generated by Django 4.1.7 on 2023-06-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_cartitems_quantity_myorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="myorders",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
