# Generated by Django 4.1.7 on 2023-06-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_myorders_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myorders",
            name="order_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
