# Generated by Django 4.1.7 on 2023-06-17 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_myorders_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="myorderitem",
            name="order_item_price",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="myorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="core.myorders",
            ),
        ),
    ]
