# Generated by Django 4.1.7 on 2023-06-17 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_myorderitem_order_item_price_alter_myorderitem_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="img",
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prod_images",
                        to="core.product",
                    ),
                ),
            ],
        ),
    ]
